### PR TITLE
#155889952 Creating retrofit classes for resources

### PR DESCRIPTION
**Pull request by Seryazi-Andela**
#### What does this PR do?
Adds classes retrofit can use to retrieve data from the web(Github API)
#### Description of Task to be completed?
Retrofit uses plain java objects to retrieve data from the internet while accessing any API so this task provides the classes retrofit will need to get data from the Github API
#### What are the relevant pivotal tracker stories?
[155889952](https://www.pivotaltracker.com/story/show/155889952)

### CODE REVIEW

**Comment by King-Benx** [comment]
@Seryazi-Andela why did you change back to JDK 7? Add steps on how these features can be manually tested and if they cannot then reflect that this can be done by looking through the code. Add docstrings and comments to provide context to your classes

**Comment by Seryazi-Andela** [comment]
Android studio keeps changing back to JDK 7 I have no idea why

**Comment by King-Benx** [comment]
You may have more than one JDK, I would suggest you make JDK 8 the default

**Comment by King-Benx** [comment]
You may have have more than one JDK version on your machine, I would suggest that you make JDK 8 the default

**Comment by King-Benx** [comment]
You may have have more than one JDK version on your machine, I would suggest that you make JDK 8 the default

**Comment by King-Benx** [comment]
> Android studio keeps changing back to JDK 7 I have no idea why

You may have have more than one JDK version on your machine, I would suggest that you make JDK 8 the default

**Comment by King-Benx** [comment]
LGTM

**Pull request merged**
