### PR TITLE
#155931587 Defining endpoints in the GithubAPI interface

### PR DESCRIPTION
**Pull request by Seryazi-Andela**
#### What does this PR do?
Adds API endpoints to the application
#### Description of Task to be completed?
The application will need to download a list of users from the api and download there details in the details activity, these two endpoints are now defined in the GithubAPI interface
#### What are the relevant pivotal tracker stories?
[155931587](https://www.pivotaltracker.com/story/show/155931587)
#### Screenshots (if appropriate)
screen shot 2018-10-23 at 11 34 37

### CODE REVIEW

**Comment by King-Benx** [comment]
@Seryazi-Andela is there any reason why this is needed?
```
@GET("?q={login} in:login")
    Call<String> getDetails(@Path("login") String login);
```

**Comment by Seryazi-Andela** [comment]
its how i get user details, login is what github api uses instead of user name

**Comment by Seryazi-Andela** [comment]
screen shot 2018-10-23 at 10 48 30

**Comment by King-Benx** [comment]
@Seryazi-Andela look through the documentation 
```https://developer.github.com/v3/search/#search-users````
There is a better way to get back the data you require with one query

**Comment by King-Benx** [comment]
LGTM

**Pull request merged**
